### ISSUE TITLE
How do you get a search box to appear?

### ISSUE THREAD

**Issue by joshjacobson** [nocodeco/Bubble-Plugin-Search-Autocorrect#6]
I'm trying to implement Demo 2, but I can't find out how to make a search box. I only can get the magnifying glass icon from this plugin.

**Comment by will-ks** [comment]
It's just a standard search box, the buit-in Bubble one. You then either set the plugin's Text to Match to the search box's value, or give the search box an ID and enter that ID in the plugin's properties.
